/**
 * action-definitions.ts — declarative Action Spine vocabulary.
 *
 * Keep behavior and validation helpers in action-registry.ts. This file is only
 * the action catalog so the registry API stays below the source-size red flag.
 */

import type { ActionDef } from "./action-registry";

export const ACTIONS: ActionDef[] = [
  // ── Workflow ──────────────────────────────────────────────────────────────
  {
    id: "workflow.create",
    description: "Create a new workflow definition as draft or validated. This does not deploy runtime triggers.",
    scope: "workflow",
    args: [
      { name: "id",          type: "string",  required: false, description: "Workflow ID. Auto-generated if omitted." },
      { name: "name",        type: "string",  required: false, description: "Human-readable name." },
      { name: "elements",    type: "array",   required: true,  description: "Array of WorkflowElement objects." },
      { name: "flow",        type: "array",   required: true,  description: "Array of FlowEdge tuples [from, to, condition?]." },
      { name: "draft",       type: "boolean", required: false, description: "Save as draft (skip trigger resolution)." },
      { name: "description", type: "string",  required: false, description: "Optional description." },
    ],
    currentEndpoint: "POST /workflows",
    autonomy: "confirm",
    audited: true,
  },
  {
    id: "workflow.update",
    description: "Update an existing workflow definition as draft or validated. This does not deploy runtime triggers.",
    scope: "workflow",
    args: [
      { name: "id",          type: "string",  required: true,  description: "Workflow ID to update." },
      { name: "name",        type: "string",  required: false, description: "New name." },
      { name: "elements",    type: "array",   required: false, description: "Updated elements array." },
      { name: "flow",        type: "array",   required: false, description: "Updated flow edges." },
      { name: "draft",       type: "boolean", required: false, description: "Save as draft." },
    ],
    currentEndpoint: "PUT /workflows/:id",
    autonomy: "confirm",
    audited: true,
  },
  {
    id: "workflow.validate",
    description: "Return the canonical workflow validation receipt with graph, runtime, deployment, and migration readiness errors and warnings.",
    scope: "workflow",
    args: [
      { name: "id", type: "string", required: true, description: "Workflow ID to validate." },
    ],
    implementation: { kind: "direct", note: "Builds the same readiness receipt used by workflow.deploy and case.start gates." },
    autonomy: "auto",
    audited: true,
  },
  {
    id: "workflow.deploy",
    description: "Validate and deploy a workflow definition, materializing runtime start triggers and marking it executable when readiness passes.",
    scope: "workflow",
    args: [
      { name: "id", type: "string", required: true, description: "Workflow ID to deploy." },
      { name: "deployed_by", type: "string", required: false, description: "Operator or agent ID recorded in lifecycle deploy metadata." },
    ],
    implementation: { kind: "direct", note: "Transitions validated workflows to executable through action-executor." },
    autonomy: "confirm",
    audited: true,
  },
  {
    id: "workflow.delete",
    description: "Archive a workflow and cascade-delete its cases.",
    scope: "workflow",
    args: [
      { name: "id", type: "string", required: true, description: "Workflow ID to archive." },
    ],
    currentEndpoint: "DELETE /workflows/:id",
    autonomy: "confirm",
    audited: true,
  },
  {
    id: "workflow.batch_delete",
    description: "Archive multiple workflows and cascade-delete their cases.",
    scope: "workflow",
    args: [
      { name: "ids", type: "array", required: true, description: "Workflow IDs to archive." },
      { name: "confirmed", type: "boolean", required: false, description: "Confirmation flag (must be true)." },
    ],
    currentEndpoint: "POST /workflows/batch-delete",
    autonomy: "confirm",
    audited: true,
  },
  {
    id: "workflow.list",
    description: "List all workflow definitions.",
    scope: "workflow",
    args: [],
    currentEndpoint: "GET /workflows",
    autonomy: "auto",
    audited: false,
  },
  {
    id: "workflow.get",
    description: "Get a single workflow definition by ID, optionally at a specific snapshot.",
    scope: "workflow",
    args: [
      { name: "id",       type: "string", required: true,  description: "Workflow ID." },
      { name: "snapshot", type: "string", required: false, description: "Snapshot version to load." },
    ],
    currentEndpoint: "GET /workflows/:id",
    autonomy: "auto",
    audited: false,
  },

  // ── Element ───────────────────────────────────────────────────────────────
  {
    id: "element.add",
    description: "Add a single element to a workflow. Updates the workflow's elements array.",
    scope: "element",
    args: [
      { name: "workflow_id", type: "string", required: true,  description: "Target workflow ID." },
      { name: "id",          type: "string", required: true,  description: "Element ID (unique within workflow)." },
      { name: "type",        type: "string", required: true,  description: "Element type: event | function | gateway." },
      { name: "label",       type: "string", required: true,  description: "Human-readable label." },
      { name: "role",        type: "string", required: false, description: "Assigned role (for functions)." },
      { name: "operator",    type: "string", required: false, description: "Gateway operator: AND | OR | XOR." },
    ],
    implementation: { kind: "direct", note: "Adds a validated element to a workflow through action-executor." },
    autonomy: "confirm",
    audited: true,
  },
  {
    id: "element.update",
    description: "Update properties of an existing element in a workflow.",
    scope: "element",
    args: [
      { name: "workflow_id", type: "string", required: true,  description: "Workflow ID." },
      { name: "id",          type: "string", required: true,  description: "Element ID to update." },
      { name: "label",       type: "string", required: false, description: "New label." },
      { name: "role",        type: "string", required: false, description: "New role assignment." },
      { name: "trigger",     type: "object", required: false, description: "Trigger configuration (for event nodes)." },
    ],
    implementation: { kind: "planned", note: "Element update action exists in the vocabulary but is not wired to executor yet." },
    autonomy: "confirm",
    audited: true,
  },
  {
    id: "element.remove",
    description: "Remove an element and its connected edges from a workflow.",
    scope: "element",
    args: [
      { name: "workflow_id", type: "string", required: true, description: "Workflow ID." },
      { name: "id",          type: "string", required: true, description: "Element ID to remove." },
    ],
    implementation: { kind: "planned", note: "Element remove action exists in the vocabulary but is not wired to executor yet." },
    autonomy: "confirm",
    audited: true,
  },

  // ── Flow ──────────────────────────────────────────────────────────────────
  {
    id: "flow.add",
    description: "Add an edge between two elements in a workflow.",
    scope: "flow",
    args: [
      { name: "workflow_id", type: "string", required: true,  description: "Workflow ID." },
      { name: "from",        type: "string", required: true,  description: "Source element ID." },
      { name: "to",          type: "string", required: true,  description: "Target element ID." },
      { name: "condition",   type: "string", required: false, description: "JS expression for conditional routing." },
    ],
    implementation: { kind: "direct", note: "Adds a validated flow edge to a workflow through action-executor." },
    autonomy: "confirm",
    audited: true,
  },
  {
    id: "flow.remove",
    description: "Remove an edge between two elements.",
    scope: "flow",
    args: [
      { name: "workflow_id", type: "string", required: true,  description: "Workflow ID." },
      { name: "from",        type: "string", required: true,  description: "Source element ID." },
      { name: "to",          type: "string", required: true,  description: "Target element ID." },
    ],
    implementation: { kind: "direct", note: "Removes a flow edge from a workflow through action-executor." },
    autonomy: "confirm",
    audited: true,
  },

  // ── Trigger ───────────────────────────────────────────────────────────────
  {
    id: "trigger.set",
    description: "Set or update the trigger configuration on an event element.",
    scope: "trigger",
    args: [
      { name: "workflow_id", type: "string", required: true,  description: "Workflow ID." },
      { name: "element_id",  type: "string", required: true,  description: "Event element ID." },
      { name: "kind",        type: "string", required: true,  description: "Trigger kind: timer | message | condition | system | manual." },
      { name: "config",      type: "object", required: false, description: "Kind-specific trigger configuration." },
    ],
    implementation: { kind: "planned", note: "Trigger mutation action exists in the vocabulary but is not wired to executor yet." },
    autonomy: "confirm",
    audited: true,
  },
  {
    id: "trigger.resolve",
    description: "Run trigger resolver on an event element to auto-detect its trigger kind.",
    scope: "trigger",
    args: [
      { name: "workflow_id", type: "string", required: true, description: "Workflow ID." },
      { name: "element_id",  type: "string", required: true, description: "Event element ID to resolve." },
    ],
    implementation: { kind: "planned", note: "Trigger resolver action exists in the vocabulary but is not wired to executor yet." },
    autonomy: "auto",
    audited: true,
  },

  // ── Case ──────────────────────────────────────────────────────────────────
  {
    id: "case.start",
    description: "Start a new case (running instance) from a workflow definition.",
    scope: "case",
    args: [
      { name: "process_id", type: "string",  required: true,  description: "Workflow ID to instantiate." },
      { name: "subject",    type: "string",  required: true,  description: "Case subject / title." },
      { name: "payload",    type: "object",  required: false, description: "Initial case data." },
      { name: "start_node", type: "string",  required: false, description: "Override start element ID." },
      { name: "admin_override", type: "boolean", required: false, description: "Explicit admin-only override for tests or migration to start a non-executable workflow." },
    ],
    currentEndpoint: "POST /cases",
    autonomy: "auto",
    audited: true,
  },
  {
    id: "case.get",
    description: "Get case details by ID.",
    scope: "case",
    args: [
      { name: "id", type: "string", required: true, description: "Case ID." },
    ],
    currentEndpoint: "GET /cases/:id",
    autonomy: "auto",
    audited: false,
  },
  {
    id: "case.list",
    description: "List cases with optional filters.",
    scope: "case",
    args: [
      { name: "status",     type: "string", required: false, description: "Filter by status: running | done | error | cancelled." },
      { name: "process_id", type: "string", required: false, description: "Filter by workflow ID." },
      { name: "limit",      type: "number", required: false, description: "Max results (default 50, max 2000)." },
      { name: "offset",     type: "number", required: false, description: "Pagination offset." },
    ],
    currentEndpoint: "GET /cases",
    autonomy: "auto",
    audited: false,
  },
  {
    id: "case.close",
    description: "Force-close a running case.",
    scope: "case",
    args: [
      { name: "id", type: "string", required: true, description: "Case ID to close." },
    ],
    currentEndpoint: "POST /cases/:id/close",
    autonomy: "confirm",
    audited: true,
  },
  {
    id: "case.cancel",
    description: "Cancel a stuck running case and release its runtime waits, subscriptions, and active work items.",
    scope: "case",
    args: [
      { name: "id",     type: "string", required: true,  description: "Case ID to cancel." },
      { name: "reason", type: "string", required: false, description: "Optional cancellation reason for audit/runtime context." },
    ],
    implementation: { kind: "direct", note: "Cancels runtime case artifacts through action-executor." },
    currentEndpoint: "POST /cases/:id/cancel",
    autonomy: "confirm",
    audited: true,
  },
  {
    id: "case.delete",
    description: "Delete a case and its related runtime work items.",
    scope: "case",
    args: [
      { name: "id", type: "string", required: true, description: "Case ID to delete." },
    ],
    implementation: { kind: "direct", note: "Deletes Redis/PG case runtime artifacts through action-executor." },
    currentEndpoint: "DELETE /cases/:id",
    autonomy: "confirm",
    audited: true,
  },

  // ── Work Item ─────────────────────────────────────────────────────────────
  {
    id: "workitem.complete",
    description: "Complete a dispatched work item, providing output data.",
    scope: "workitem",
    args: [
      { name: "id",     type: "string", required: true,  description: "Work item ID." },
      { name: "output", type: "object", required: false, description: "Output data from task execution." },
    ],
    currentEndpoint: "POST /workitems/:id/complete",
    autonomy: "auto",
    audited: true,
  },
  {
    id: "workitem.create",
    description: "Create a standalone work item (not tied to a case).",
    scope: "workitem",
    args: [
      { name: "label",    type: "string", required: true,  description: "Work item title." },
      { name: "assignee", type: "string", required: true,  description: "Role or agent ID to assign to." },
      { name: "input",    type: "object", required: false, description: "Input data." },
      { name: "deadline", type: "string", required: false, description: "ISO 8601 deadline." },
      { name: "process_id", type: "string", required: false, description: "Optional workflow/process ID for standalone work item grouping." },
    ],
    currentEndpoint: "POST /workitems",
    autonomy: "auto",
    audited: true,
  },
  {
    id: "workitem.update",
    description: "Update work item status, assignee, deadline, or output.",
    scope: "workitem",
    args: [
      { name: "id",       type: "string", required: true,  description: "Work item ID." },
      { name: "status",   type: "string", required: false, description: "New status." },
      { name: "assignee", type: "string", required: false, description: "New assignee." },
      { name: "deadline", type: "string", required: false, description: "New deadline." },
      { name: "output",   type: "object", required: false, description: "Output data." },
      { name: "label",    type: "string", required: false, description: "New work item label." },
    ],
    currentEndpoint: "PATCH /workitems/:id",
    autonomy: "auto",
    audited: true,
  },
  {
    id: "workitem.list",
    description: "List work items with optional filters.",
    scope: "workitem",
    args: [
      { name: "assignee",       type: "string", required: false, description: "Filter by assignee." },
      { name: "status",         type: "string", required: false, description: "Filter by status." },
      { name: "process_id",     type: "string", required: false, description: "Filter by workflow ID." },
      { name: "case_id",        type: "string", required: false, description: "Filter by case/run ID." },
      { name: "deadline_before", type: "string", required: false, description: "Only items due before this date." },
    ],
    currentEndpoint: "GET /workitems",
    autonomy: "auto",
    audited: false,
  },
  {
    id: "workitem.cancel",
    description: "Cancel a work item.",
    scope: "workitem",
    args: [
      { name: "id", type: "string", required: true, description: "Work item ID to cancel." },
    ],
    currentEndpoint: "DELETE /workitems/:id",
    autonomy: "auto",
    audited: true,
  },

  // ── Role ──────────────────────────────────────────────────────────────────
  {
    id: "role.create",
    description: "Create a new role definition.",
    scope: "role",
    args: [
      { name: "role_id",     type: "string", required: true,  description: "Unique role identifier." },
      { name: "name",        type: "string", required: true,  description: "Display name." },
      { name: "description", type: "string", required: false, description: "Role description." },
      { name: "assignees",   type: "array",  required: false, description: "Initial role assignee IDs." },
      { name: "strategy",    type: "string", required: false, description: "Assignment strategy." },
    ],
    currentEndpoint: "POST /roles",
    autonomy: "confirm",
    audited: true,
  },
  {
    id: "role.list",
    description: "List all roles.",
    scope: "role",
    args: [],
    currentEndpoint: "GET /roles",
    autonomy: "auto",
    audited: false,
  },
  {
    id: "role.update",
    description: "Update a role definition.",
    scope: "role",
    args: [
      { name: "id",          type: "string", required: true,  description: "Role ID." },
      { name: "name",        type: "string", required: false, description: "New display name." },
      { name: "description", type: "string", required: false, description: "New description." },
      { name: "assignees",   type: "array",  required: false, description: "Updated role assignee IDs." },
      { name: "strategy",    type: "string", required: false, description: "New assignment strategy." },
    ],
    currentEndpoint: "PATCH /roles/:id",
    autonomy: "confirm",
    audited: true,
  },
  {
    id: "role.delete",
    description: "Delete a role definition.",
    scope: "role",
    args: [
      { name: "id", type: "string", required: true, description: "Role ID to delete." },
    ],
    currentEndpoint: "DELETE /roles/:id",
    autonomy: "confirm",
    audited: true,
  },

  // ── Agent ─────────────────────────────────────────────────────────────────
  {
    id: "agent.register",
    description: "Register an agent on the bus.",
    scope: "agent",
    args: [
      { name: "id",            type: "string", required: true,  description: "Unique agent ID." },
      { name: "name",          type: "string", required: true,  description: "Display name." },
      { name: "display_alias", type: "string", required: false, description: "Instance-specific alias/callsign." },
      { name: "roles",         type: "array",  required: false, description: "Role list." },
      { name: "capabilities",  type: "array",  required: false, description: "Capability list." },
      { name: "model",         type: "string", required: false, description: "Model identifier." },
    ],
    currentEndpoint: "POST /agents/register",
    autonomy: "auto",
    audited: true,
  },
  {
    id: "agent.update_profile",
    description: "Update canonical and operator-editable agent profile fields.",
    scope: "agent",
    args: [
      { name: "id",               type: "string", required: true,  description: "Agent ID to update." },
      { name: "name",             type: "string", required: false, description: "Canonical corporate/product agent name." },
      { name: "display_alias",    type: "string", required: false, description: "Instance-specific alias/callsign." },
      { name: "system_prompt",    type: "string", required: false, description: "User-maintained agent instructions." },
      { name: "runtime",          type: "string", required: false, description: "Runtime adapter." },
      { name: "fallback_runtime", type: "string", required: false, description: "Fallback runtime adapter." },
      { name: "model",                     type: "string", required: false, description: "Model identifier." },
      { name: "llm_client_profile",       type: "string", required: false, description: "LLM client profile for provider/model resolution." },
      { name: "fallback_llm_client_profile", type: "string", required: false, description: "Fallback LLM client profile." },
      { name: "reasoning_effort",          type: "string", required: false, description: "Provider-specific reasoning effort." },
      { name: "capabilities",     type: "array",  required: false, description: "Skill/capability IDs." },
      { name: "gender",           type: "string", required: false, description: "Grammatical gender for copy and prompts." },
    ],
    currentEndpoint: "PUT /agents/:id",
    autonomy: "confirm",
    audited: true,
  },
  {
    id: "agent.start",
    description: "Start a stopped agent (creates tmux session).",
    scope: "agent",
    args: [
      { name: "id", type: "string", required: true, description: "Agent ID to start." },
    ],
    currentEndpoint: "POST /agents/:id/start",
    autonomy: "confirm",
    audited: true,
  },
  {
    id: "agent.stop",
    description: "Stop a running agent.",
    scope: "agent",
    args: [
      { name: "id", type: "string", required: true, description: "Agent ID to stop." },
    ],
    currentEndpoint: "POST /agents/:id/stop",
    autonomy: "confirm",
    audited: true,
  },
  {
    id: "agent.restart",
    description: "Restart an agent (stop + start, regenerates config).",
    scope: "agent",
    args: [
      { name: "id", type: "string", required: true, description: "Agent ID to restart." },
    ],
    currentEndpoint: "POST /agents/:id/restart",
    autonomy: "confirm",
    audited: true,
  },

  // ── Person Directory ──────────────────────────────────────────────────────
  {
    id: "person.list",
    description: "List people from trusted-users file and custom dashboard records.",
    scope: "person",
    args: [],
    currentEndpoint: "GET /people",
    autonomy: "auto",
    audited: false,
  },
  {
    id: "person.upsert",
    description: "Create or update a custom person record. File-backed trusted users cannot be overridden.",
    scope: "person",
    args: [
      { name: "id",             type: "string", required: false, description: "Stable person ID. Generated from name if omitted." },
      { name: "name",           type: "string", required: true,  description: "Display name." },
      { name: "tg_id",          type: "number", required: false, description: "Telegram numeric user ID." },
      { name: "tg_username",    type: "string", required: false, description: "Telegram username without @." },
      { name: "position",       type: "string", required: false, description: "Role or job title." },
      { name: "email",          type: "string", required: false, description: "Email address." },
      { name: "bitrix24_id",    type: "string", required: false, description: "Bitrix24 user ID." },
      { name: "tracker_login",  type: "string", required: false, description: "Yandex Tracker login." },
      { name: "yonote_id",      type: "string", required: false, description: "Yonote user ID." },
      { name: "channel",        type: "string", required: false, description: "Preferred notification channel: telegram | email." },
      { name: "capabilities",   type: "array",  required: false, description: "Capability/skill IDs." },
      { name: "avatar_url",     type: "string", required: false, description: "Avatar URL." },
    ],
    currentEndpoint: "POST /people",
    autonomy: "confirm",
    audited: true,
  },
  {
    id: "person.delete",
    description: "Delete a custom person record. File-backed trusted users cannot be deleted here.",
    scope: "person",
    args: [
      { name: "id", type: "string", required: true, description: "Person ID to delete." },
    ],
    currentEndpoint: "DELETE /people/:id",
    autonomy: "confirm",
    audited: true,
  },

  // ── Access Control ────────────────────────────────────────────────────────
  {
    id: "access.list",
    description: "List owner, trusted users, whitelisted Telegram groups, and pending access requests.",
    scope: "access",
    args: [],
    currentEndpoint: "GET /whitelist",
    autonomy: "auto",
    audited: false,
  },
  {
    id: "access.approve",
    description: "Approve a pending user or group access request.",
    scope: "access",
    args: [
      { name: "type",        type: "string", required: true,  description: "Entry type: user | group." },
      { name: "telegram_id", type: "number", required: false, description: "Telegram user ID for user approvals." },
      { name: "chat_id",     type: "number", required: false, description: "Telegram chat ID for group approvals." },
    ],
    currentEndpoint: "POST /whitelist/approve",
    autonomy: "confirm",
    audited: true,
  },
  {
    id: "access.reject",
    description: "Reject a pending user or group access request, optionally blocking it.",
    scope: "access",
    args: [
      { name: "type",        type: "string",  required: true,  description: "Entry type: user | group." },
      { name: "telegram_id", type: "number",  required: false, description: "Telegram user ID for user rejections." },
      { name: "chat_id",     type: "number",  required: false, description: "Telegram chat ID for group rejections." },
      { name: "block",       type: "boolean", required: false, description: "Add ID to blocked list." },
    ],
    currentEndpoint: "POST /whitelist/reject",
    autonomy: "confirm",
    audited: true,
  },
  {
    id: "access.upsert_user",
    description: "Create or update a trusted Telegram user in the file-backed access list.",
    scope: "access",
    args: [
      { name: "name",        type: "string", required: true,  description: "Display name." },
      { name: "telegram_id", type: "number", required: true,  description: "Telegram numeric user ID." },
      { name: "username",    type: "string", required: false, description: "Telegram username without @." },
      { name: "email",       type: "string", required: false, description: "Email address." },
      { name: "phone",       type: "string", required: false, description: "Phone number." },
      { name: "position",    type: "string", required: false, description: "Role or job title." },
      { name: "relation",    type: "string", required: false, description: "Relation/group label." },
      { name: "level",       type: "number", required: false, description: "Trust level." },
    ],
    currentEndpoint: "POST /whitelist/user",
    autonomy: "confirm",
    audited: true,
  },
  {
    id: "access.remove_user",
    description: "Remove a trusted Telegram user from the access list.",
    scope: "access",
    args: [
      { name: "telegram_id", type: "number", required: true, description: "Telegram numeric user ID." },
    ],
    currentEndpoint: "DELETE /whitelist/user/:telegram_id",
    autonomy: "confirm",
    audited: true,
  },
  {
    id: "access.add_group",
    description: "Add a Telegram group to the whitelist.",
    scope: "access",
    args: [
      { name: "chat_id", type: "number", required: true, description: "Telegram chat ID." },
    ],
    currentEndpoint: "POST /whitelist/group",
    autonomy: "confirm",
    audited: true,
  },
  {
    id: "access.remove_group",
    description: "Remove a Telegram group from the whitelist.",
    scope: "access",
    args: [
      { name: "chat_id", type: "number", required: true, description: "Telegram chat ID." },
    ],
    currentEndpoint: "DELETE /whitelist/group/:chat_id",
    autonomy: "confirm",
    audited: true,
  },

  // ── Subscription (Event Manager) ──────────────────────────────────────────
  {
    id: "subscription.create",
    description: "Create an event subscription for trigger-based case activation or resumption.",
    scope: "subscription",
    args: [
      { name: "event_id",    type: "string", required: true,  description: "Event element ID." },
      { name: "process_id",  type: "string", required: true,  description: "Process definition ID." },
      { name: "instance_id", type: "string", required: true,  description: "Case ID or 'new' for auto-create." },
      { name: "trigger",     type: "object", required: true,  description: "Trigger definition (TriggerDef)." },
    ],
    currentEndpoint: "POST /api/event-manager/subscribe",
    autonomy: "auto",
    audited: true,
  },
  {
    id: "subscription.cancel",
    description: "Cancel an active event subscription.",
    scope: "subscription",
    args: [
      { name: "id", type: "string", required: true, description: "Subscription ID to cancel." },
    ],
    currentEndpoint: "DELETE /api/event-manager/subscribe/:id",
    autonomy: "auto",
    audited: true,
  },
  {
    id: "subscription.list",
    description: "List all active event subscriptions.",
    scope: "subscription",
    args: [],
    currentEndpoint: "GET /api/event-manager/subscriptions",
    autonomy: "auto",
    audited: false,
  },

  // ── Retention ────────────────────────────────────────────────────────────
  {
    id: "retention.report",
    description: "Generate a read-only PG-only runtime artifact retention report. Does not delete or update data.",
    scope: "retention",
    args: [
      { name: "limit", type: "number", required: false, description: "Maximum number of candidate groups to return. Omit for default; use 0 for counts only." },
    ],
    implementation: { kind: "direct", note: "Handled by executeActionDirect; destructive cleanup is intentionally not implemented yet." },
    autonomy: "auto",
    audited: false,
  },
  {
    id: "retention.cleanup_preview",
    description: "Preview exact safe retention cleanup candidates. Does not delete or update data.",
    scope: "retention",
    args: [
      { name: "limit", type: "number", required: false, description: "Maximum number of candidate IDs to return. Omit for default." },
    ],
    implementation: { kind: "direct", note: "Read-only preview; destructive cleanup is intentionally not implemented yet." },
    autonomy: "confirm",
    audited: false,
  },
  {
    id: "retention.cleanup_apply",
    description: "Delete exact PG-only safe retention candidates after explicit admin confirmation.",
    scope: "retention",
    args: [
      { name: "confirm", type: "boolean", required: true, description: "Must be true to apply cleanup." },
      { name: "candidates", type: "array", required: true, description: "Exact candidates returned by retention.cleanup_preview: { entity, id, candidate }." },
    ],
    implementation: { kind: "direct", note: "All-or-nothing PG-only cleanup; revalidates candidates before deleting." },
    autonomy: "confirm",
    audited: true,
  },
  {
    id: "retention.runtime_cleanup",
    description: "Clean up expired Redis-primary runtime cases and workflow runs that are safe for automatic deletion.",
    scope: "retention",
    args: [
      { name: "dry_run", type: "boolean", required: false, description: "Preview without deleting. Defaults to true." },
      { name: "stuck_case_ttl_hours", type: "number", required: false, description: "Minimum age for stuck running cases." },
      { name: "completed_workflow_ttl_hours", type: "number", required: false, description: "Minimum age for completed workflow runs." },
      { name: "max_delete", type: "number", required: false, description: "Maximum cases to delete in one run." },
    ],
    implementation: { kind: "direct", note: "Deletes only generated/test runtime cases or cases explicitly opted into auto-delete." },
    autonomy: "confirm",
    audited: true,
  },

  // ── Issue (GitHub) ────────────────────────────────────────────────────────
  {
    id: "issue.create",
    description: "Create a GitHub issue in the konoha repo.",
    scope: "issue",
    args: [
      { name: "title",    type: "string", required: true,  description: "Issue title." },
      { name: "body",     type: "string", required: true,  description: "Issue body (markdown)." },
      { name: "priority", type: "string", required: false, description: "Priority label: priority:p0 | priority:p1 | priority:p2 | priority:p3." },
      { name: "labels",   type: "array",  required: false, description: "Additional labels." },
    ],
    implementation: { kind: "registered-handler", note: "Registered in action-handlers.ts." },
    autonomy: "auto",
    audited: true,
  },
  {
    id: "issue.get",
    description: "Get a GitHub issue with labels, comments, and body.",
    scope: "issue",
    args: [
      { name: "issue_number", type: "number",  required: true,  description: "GitHub issue number." },
      { name: "repo",         type: "string",  required: false, description: "GitHub repo, defaults to eaprelsky/konoha." },
      { name: "dry_run",      type: "boolean", required: false, description: "Return the gh command without executing it." },
    ],
    implementation: { kind: "direct", note: "Uses gh issue view with JSON output." },
    autonomy: "auto",
    audited: false,
  },
  {
    id: "issue.list",
    description: "List GitHub issues with optional state and label filters.",
    scope: "issue",
    args: [
      { name: "repo",    type: "string",  required: false, description: "GitHub repo, defaults to eaprelsky/konoha." },
      { name: "state",   type: "string",  required: false, description: "Issue state: open | closed | all." },
      { name: "labels",  type: "array",   required: false, description: "Labels that must be present." },
      { name: "limit",   type: "number",  required: false, description: "Maximum issues to return." },
      { name: "dry_run", type: "boolean", required: false, description: "Return the gh command without executing it." },
    ],
    implementation: { kind: "direct", note: "Uses gh issue list with JSON output." },
    autonomy: "auto",
    audited: false,
  },
  {
    id: "issue.comment",
    description: "Add a comment to a GitHub issue.",
    scope: "issue",
    args: [
      { name: "issue_number", type: "number",  required: true,  description: "GitHub issue number." },
      { name: "body",         type: "string",  required: true,  description: "Comment body." },
      { name: "repo",         type: "string",  required: false, description: "GitHub repo, defaults to eaprelsky/konoha." },
      { name: "dry_run",      type: "boolean", required: false, description: "Return the gh command without executing it." },
    ],
    implementation: { kind: "direct", note: "Uses gh issue comment." },
    autonomy: "auto",
    audited: true,
  },
  {
    id: "issue.update_labels",
    description: "Add and/or remove labels on a GitHub issue.",
    scope: "issue",
    args: [
      { name: "issue_number",  type: "number",  required: true,  description: "GitHub issue number." },
      { name: "add_labels",    type: "array",   required: false, description: "Labels to add." },
      { name: "remove_labels", type: "array",   required: false, description: "Labels to remove." },
      { name: "repo",          type: "string",  required: false, description: "GitHub repo, defaults to eaprelsky/konoha." },
      { name: "dry_run",       type: "boolean", required: false, description: "Return the gh command without executing it." },
    ],
    implementation: { kind: "direct", note: "Uses gh issue edit --add-label/--remove-label." },
    autonomy: "auto",
    audited: true,
  },
  {
    id: "issue.close",
    description: "Close a GitHub issue, optionally with a closing comment.",
    scope: "issue",
    args: [
      { name: "issue_number", type: "number",  required: true,  description: "GitHub issue number." },
      { name: "comment",      type: "string",  required: false, description: "Optional closing comment." },
      { name: "repo",         type: "string",  required: false, description: "GitHub repo, defaults to eaprelsky/konoha." },
      { name: "dry_run",      type: "boolean", required: false, description: "Return the gh command without executing it." },
    ],
    implementation: { kind: "direct", note: "Uses gh issue close." },
    autonomy: "auto",
    audited: true,
  },

  // ── Reminder ──────────────────────────────────────────────────────────────
  {
    id: "reminder.create",
    description: "Create a scheduled reminder.",
    scope: "reminder",
    args: [
      { name: "type",         type: "string", required: false, description: "Reminder type, defaults to standalone." },
      { name: "recipient",    type: "string", required: true,  description: "Agent or person ID." },
      { name: "message",      type: "string", required: true,  description: "Reminder message text." },
      { name: "scheduled_at", type: "string", required: true,  description: "ISO 8601 scheduled time." },
      { name: "channel",      type: "string", required: false, description: "Delivery channel: gui | telegram." },
      { name: "case_id",      type: "string", required: false, description: "Related case ID." },
      { name: "process_id",   type: "string", required: false, description: "Related workflow/process ID." },
      { name: "element_id",   type: "string", required: false, description: "Related workflow element ID." },
      { name: "work_item_id", type: "string", required: false, description: "Related work item ID." },
    ],
    currentEndpoint: "POST /reminders",
    autonomy: "auto",
    audited: true,
  },
  {
    id: "reminder.list",
    description: "List reminders with optional filters.",
    scope: "reminder",
    args: [
      { name: "status",    type: "string", required: false, description: "Filter by status." },
      { name: "recipient", type: "string", required: false, description: "Filter by recipient." },
    ],
    currentEndpoint: "GET /reminders",
    autonomy: "auto",
    audited: false,
  },
  {
    id: "reminder.update_status",
    description: "Update reminder status (e.g. mark as sent).",
    scope: "reminder",
    args: [
      { name: "id",     type: "string", required: true, description: "Reminder ID." },
      { name: "status", type: "string", required: true, description: "New status." },
    ],
    currentEndpoint: "PATCH /reminders/:id/status",
    autonomy: "auto",
    audited: true,
  },
  {
    id: "reminder.delete",
    description: "Delete a reminder.",
    scope: "reminder",
    args: [
      { name: "id", type: "string", required: true, description: "Reminder ID." },
    ],
    currentEndpoint: "DELETE /reminders/:id",
    autonomy: "auto",
    audited: true,
  },

  // ── Message ───────────────────────────────────────────────────────────────
  {
    id: "message.send",
    description: "Send a message to an agent, role group, or broadcast.",
    scope: "message",
    args: [
      { name: "to",   type: "string", required: true,  description: "Recipient: agent ID, 'all', or 'role:<role>'." },
      { name: "text", type: "string", required: true,  description: "Message text (max 32768 chars)." },
      { name: "type", type: "string", required: false, description: "Message type: message | task | result | status | event." },
    ],
    currentEndpoint: "POST /messages",
    autonomy: "auto",
    audited: true,
  },
  {
    id: "message.read",
    description: "Read new (unacknowledged) messages for an agent.",
    scope: "message",
    args: [
      { name: "agent_id", type: "string", required: true,  description: "Agent ID to read for." },
      { name: "count",    type: "number", required: false, description: "Max messages to return." },
    ],
    currentEndpoint: "GET /messages/:agentId",
    autonomy: "auto",
    audited: false,
  },

  // ── Assistants ───────────────────────────────────────────────────────────
  {
    id: "assistant.invoke",
    description: "Invoke a product assistant in deterministic non-streaming mode for API/MCP/testbench scenarios.",
    scope: "assistant",
    args: [
      { name: "assistant_id",        type: "string",  required: true,  description: "Assistant ID, currently tsunade or kiba." },
      { name: "message",             type: "string",  required: true,  description: "User message to send to the assistant." },
      { name: "conversation_id",     type: "string",  required: false, description: "Stable conversation ID. Generated if omitted." },
      { name: "context",             type: "object",  required: false, description: "Optional structured context or fixture payload." },
      { name: "operator_state",      type: "object",  required: false, description: "Optional operator/page state for future UI parity." },
      { name: "schema",              type: "object",  required: false, description: "Optional workflow/schema context for Tsunade." },
      { name: "stream",              type: "boolean", required: false, description: "Must be false or omitted; streaming is intentionally out of scope for this action." },
      { name: "execute_actions",     type: "boolean", required: false, description: "Whether normalized assistant actions may execute. Defaults to true." },
      { name: "persist_history",     type: "boolean", required: false, description: "Whether to persist conversation history. Defaults to true." },
      { name: "fixture_response",    type: "string",  required: false, description: "Deterministic raw assistant response for regression tests." },
      { name: "include_raw_response", type: "boolean", required: false, description: "Include raw assistant output in the result for debugging." },
    ],
    implementation: { kind: "direct", note: "Reuses the server-side assistant response normalizer for testbench-safe invocation." },
    security: { actor: "authenticated" },
    autonomy: "confirm",
    audited: true,
  },

  // ── Connectors ───────────────────────────────────────────────────────────
  {
    id: "connector.send_message",
    description: "Send an outbound message through a messenger connector endpoint.",
    scope: "connector",
    args: [
      { name: "connector_id", type: "string",  required: true,  description: "Connector ID, e.g. telegram-main." },
      { name: "endpoint_id",  type: "string",  required: true,  description: "Endpoint ID under the connector." },
      { name: "chat_ref",     type: "string",  required: true,  description: "Provider chat reference." },
      { name: "text",         type: "string",  required: true,  description: "Message text." },
      { name: "reply_to",     type: "string",  required: false, description: "Provider message id to reply to." },
      { name: "parse_mode",   type: "string",  required: false, description: "Provider parse mode when supported." },
      { name: "dry_run",      type: "boolean", required: false, description: "Validate and build the outbound message without publishing it." },
      { name: "metadata",     type: "object",  required: false, description: "Optional audit/debug metadata." },
    ],
    implementation: { kind: "direct", note: "Writes connector-normalized messages to the outbound transport stream." },
    security: { actor: "authenticated" },
    autonomy: "confirm",
    audited: true,
  },

  // ── Audit ─────────────────────────────────────────────────────────────────
  {
    id: "audit.read",
    description: "Read the action audit log with optional filters.",
    scope: "audit",
    args: [
      { name: "action_type", type: "string", required: false, description: "Filter by action type." },
      { name: "agent",       type: "string", required: false, description: "Filter by agent." },
      { name: "from_date",   type: "string", required: false, description: "Start date filter." },
      { name: "to_date",     type: "string", required: false, description: "End date filter." },
      { name: "limit",       type: "number", required: false, description: "Max entries to return." },
    ],
    currentEndpoint: "GET /audit",
    autonomy: "auto",
    audited: false,
  },

  // ── Event (manual confirmation) ───────────────────────────────────────────
  {
    id: "event.confirm",
    description: "Confirm a manual event wait, advancing the case past the current event node.",
    scope: "case",
    args: [
      { name: "case_id",      type: "string", required: true,  description: "Case ID to confirm event for." },
      { name: "element_id",   type: "string", required: false, description: "Event element ID (defaults to current position)." },
      { name: "comment",      type: "string", required: false, description: "Optional confirmation comment." },
      { name: "confirmed_by", type: "string", required: true,  description: "User ID of the confirmer." },
      { name: "outcome",      type: "string", required: false, description: "Outcome for approval gates: approved | rejected." },
    ],
    currentEndpoint: "POST /events/mining/case/:id/confirm-event",
    autonomy: "auto",
    audited: true,
  },
  {
    id: "event.wait_list",
    description: "List active manual event waits (inbox), optionally filtered by assignee.",
    scope: "case",
    args: [
      { name: "assignee", type: "string", required: false, description: "Filter by assignee role or user ID." },
      { name: "status",   type: "string", required: false, description: "Filter by wait status: active | overdue | escalated." },
    ],
    implementation: { kind: "planned", note: "Manual wait inbox action is registered but still needs direct endpoint/executor wiring." },
    autonomy: "auto",
    audited: false,
  },

  // ── Knowledge ─────────────────────────────────────────────────────────────
  {
    id: "knowledge.tree",
    description: "Get the knowledge base file tree.",
    scope: "knowledge",
    args: [],
    currentEndpoint: "GET /api/kb/tree",
    autonomy: "auto",
    audited: false,
  },
  {
    id: "knowledge.read",
    description: "Read a file from the knowledge base.",
    scope: "knowledge",
    args: [
      { name: "path", type: "string", required: true, description: "Relative file path." },
    ],
    currentEndpoint: "GET /api/kb/file",
    autonomy: "auto",
    audited: false,
  },
  {
    id: "knowledge.search",
    description: "Full-text search in knowledge base markdown files.",
    scope: "knowledge",
    args: [
      { name: "q", type: "string", required: true, description: "Search query." },
    ],
    currentEndpoint: "GET /api/kb/search",
    autonomy: "auto",
    audited: false,
  },
];
